# Generated by Django 4.2.3 on 2023-07-17 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bajetiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('date_added', models.DateField()),
                ('user_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='budgetinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
        migrations.DeleteModel(
            name='BudgetInfo',
        ),
    ]
