version: '3.9'
services:
  app:
    container_name: golang_container
    env_file:
      - .env
    tty: true
    build: .
    ports:
      - "8000:8080"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - bajeti

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "1234:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - bajeti

volumes:
  pg_data:

networks:
  bajeti:
    driver: bridge
